services:
  postgres:
    image: postgres:12-alpine
    environment:
      -  POSTGRES_USER=root
      -  POSTGRES_PASSWORD=secret
      -  POSTGRES_DB=simple_bank
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data
  
  redis:
    image: redis:7-alpine
  
  api:
    build:
    # . meanings is current root folder. (Project folder)
      context: .
      # Dockerfile is in root of the project
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
      - REDIS_ADDRESS=redis:6379
    # Make sure that the postgres will be started before the api service
    depends_on:
      - postgres
      - redis
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
volumes:
  data-volume: