package db

import (
	"context"
	"database/sql"
	"fmt"
)

// * Note [codermuss]: Make interface for mocking
type Store interface {
	// * Note [codermuss]: Querier generated by sqlc. It has an interface includes all db functions.
	// * Note [codermuss]: If sqlc would not generate this. We would have to write all db functions by manually.
	Querier
	// * Note [codermuss]:
	TransferTx(ctx context.Context, arg TransferTxParams) (TransferTxResult, error)
	CreateUserTx(ctx context.Context, arg CreateUserTxParams) (CreateUserTxResult, error)
	VerifyEmailTx(ctx context.Context, arg VerifyEmailTxParams) (VerifyEmailTxResult, error)
}

type SQLStore struct {
	*Queries
	db *sql.DB
}

// * Note [codermuss]: SQL Store implements the Store interface so this func can return SQLStore
func NewStore(db *sql.DB) Store {
	return &SQLStore{
		db:      db,
		Queries: New(db),
	}
}

func (store *SQLStore) execTx(ctx context.Context, fn func(*Queries) error) error {
	tx, err := store.db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	// * Note [codermuss]: Begin db transaction
	q := New(tx)
	// * Note [codermuss]: execute query
	err = fn(q)
	// * Note [codermuss]: if there is an error Rollback the query
	if err != nil {
		if rbErr := tx.Rollback(); rbErr != nil {
			return fmt.Errorf("tx err: %v, rb err: %v", err, rbErr)
		}
		return err
	}
	return tx.Commit()
}
