// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: rpc_add_account.proto

package simplebank

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddAccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Currency string `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
}

func (x *AddAccountRequest) Reset() {
	*x = AddAccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_add_account_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAccountRequest) ProtoMessage() {}

func (x *AddAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_add_account_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAccountRequest.ProtoReflect.Descriptor instead.
func (*AddAccountRequest) Descriptor() ([]byte, []int) {
	return file_rpc_add_account_proto_rawDescGZIP(), []int{0}
}

func (x *AddAccountRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type AddAccountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account *Accounts `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
}

func (x *AddAccountResponse) Reset() {
	*x = AddAccountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_add_account_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAccountResponse) ProtoMessage() {}

func (x *AddAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_add_account_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAccountResponse.ProtoReflect.Descriptor instead.
func (*AddAccountResponse) Descriptor() ([]byte, []int) {
	return file_rpc_add_account_proto_rawDescGZIP(), []int{1}
}

func (x *AddAccountResponse) GetAccount() *Accounts {
	if x != nil {
		return x.Account
	}
	return nil
}

var File_rpc_add_account_proto protoreflect.FileDescriptor

var file_rpc_add_account_proto_rawDesc = []byte{
	0x0a, 0x15, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x64, 0x64, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x17, 0x72, 0x70, 0x63,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2f, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x22, 0x3c, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x07, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70,
	0x62, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6d, 0x75, 0x73, 0x74, 0x61, 0x66, 0x61, 0x79, 0x69, 0x6c, 0x6d, 0x61, 0x7a, 0x64,
	0x65, 0x76, 0x2f, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x62, 0x61, 0x6e, 0x6b, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_add_account_proto_rawDescOnce sync.Once
	file_rpc_add_account_proto_rawDescData = file_rpc_add_account_proto_rawDesc
)

func file_rpc_add_account_proto_rawDescGZIP() []byte {
	file_rpc_add_account_proto_rawDescOnce.Do(func() {
		file_rpc_add_account_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_add_account_proto_rawDescData)
	})
	return file_rpc_add_account_proto_rawDescData
}

var file_rpc_add_account_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_add_account_proto_goTypes = []any{
	(*AddAccountRequest)(nil),  // 0: pb.AddAccountRequest
	(*AddAccountResponse)(nil), // 1: pb.AddAccountResponse
	(*Accounts)(nil),           // 2: pb.Accounts
}
var file_rpc_add_account_proto_depIdxs = []int32{
	2, // 0: pb.AddAccountResponse.account:type_name -> pb.Accounts
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_add_account_proto_init() }
func file_rpc_add_account_proto_init() {
	if File_rpc_add_account_proto != nil {
		return
	}
	file_rpc_list_accounts_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_add_account_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AddAccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_add_account_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AddAccountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_add_account_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_add_account_proto_goTypes,
		DependencyIndexes: file_rpc_add_account_proto_depIdxs,
		MessageInfos:      file_rpc_add_account_proto_msgTypes,
	}.Build()
	File_rpc_add_account_proto = out.File
	file_rpc_add_account_proto_rawDesc = nil
	file_rpc_add_account_proto_goTypes = nil
	file_rpc_add_account_proto_depIdxs = nil
}
